
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: invalid
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: feedforward_development

test:
  <<: *default
  database: feedforward_test


#
production:
  <<: *default
  database: feedforward_production
  username: feedforward
  password: <%= ENV['FEEDFORWARD_DATABASE_PASSWORD'] %>
